name: Build Single App
on:
  workflow_dispatch:
    inputs:
        app_to_build:
          description: 'Which app to build?'
          required: true
          type: choice
          options:
            - bazarr
            - stashapp
            - tautulli
            - jellyseerr
        force_build:
          description: 'Build even if no new version (test build, no release)'
          type: boolean
          default: false

permissions:
  contents: write

jobs:
  app:
    uses: ./.github/workflows/build.yml
    with:
      APP: ${{ inputs.app_to_build }}
      FORCE_BUILD: ${{ inputs.force_build }}
    secrets: inherit
