name: Build Single App
on:
  workflow_dispatch:
    inputs:
        app_to_build:
          description: 'Which app to build?'
          required: true
          type: choice
          options:
            - bazarr
            - stashapp
            - tautulli
            - jellyseerr
        force_build:
          description: 'Build even if no new version (test build, no release)'
          type: boolean
          default: false

permissions:
  contents: write
  packages: read

jobs:
  bazarr:
    if: github.event.inputs.app_to_build == 'bazarr'
    uses: ./.github/workflows/build.yml
    with:
      APP: bazarr
      UPSTREAM: morpheus65535/bazarr
      FORCE_BUILD: ${{ inputs.force_build }}
    secrets: inherit

  stashapp:
    if: github.event.inputs.app_to_build == 'stashapp'
    uses: ./.github/workflows/build.yml
    with:
      APP: stashapp
      UPSTREAM: stashapp/stash
      FORCE_BUILD: ${{ inputs.force_build }}
    secrets: inherit

  tautulli:
    if: github.event.inputs.app_to_build == 'tautulli'
    uses: ./.github/workflows/build.yml
    with:
      APP: tautulli
      UPSTREAM: tautulli/tautulli
      FORCE_BUILD: ${{ inputs.force_build }}
    secrets: inherit

  jellyseerr:
    if: github.event.inputs.app_to_build == 'jellyseerr'
    uses: ./.github/workflows/build.yml
    with:
      APP: jellyseerr
      UPSTREAM: fallenbagel/jellyseerr
      FORCE_BUILD: ${{ inputs.force_build }}
    secrets: inherit
