name: Build All
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bazarr:
    uses: ./.github/workflows/build.yml
    with:
      APP: bazarr
      UPSTREAM: morpheus65535/bazarr
    secrets: inherit

  stashapp:
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/build.yml
    with:
      APP: stashapp
      UPSTREAM: stashapp/stash
    secrets: inherit

  tautulli:
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/build.yml
    with:
      APP: tautulli
      UPSTREAM: tautulli/tautulli
    secrets: inherit

  jellyseerr:
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/build.yml
    with:
      APP: jellyseerr
      UPSTREAM: seerr-team/seerr
    secrets: inherit
