name: Build All          
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      app_to_build:
        description: 'Which app to build?'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - bazarr
          - stashapp
          - tautulli
          - jellyseerr

permissions:
  contents: write
  packages: read

jobs:
  bazarr:
    if: github.event_name == 'schedule' || github.event.inputs.app_to_build == 'all' || github.event.inputs.app_to_build == 'bazarr'
    uses: ./.github/workflows/build.yml
    with:
      APP: bazarr
      UPSTREAM: morpheus65535/bazarr
    secrets: inherit     

  stashapp:
    needs: bazarr
    if: github.event_name == 'schedule' || github.event.inputs.app_to_build == 'all' || github.event.inputs.app_to_build == 'stashapp'
    uses: ./.github/workflows/build.yml
    with:
      APP: stashapp
      UPSTREAM: stashapp/stash
    secrets: inherit     

  tautulli:
    needs: stashapp
    if: github.event_name == 'schedule' || github.event.inputs.app_to_build == 'all' || github.event.inputs.app_to_build == 'tautulli'
    uses: ./.github/workflows/build.yml
    with:
      APP: tautulli
      UPSTREAM: tautulli/tautulli
    secrets: inherit     

  jellyseerr:
    needs: tautulli
    if: github.event_name == 'schedule' || github.event.inputs.app_to_build == 'all' || github.event.inputs.app_to_build == 'jellyseerr'
    uses: ./.github/workflows/build.yml
    with:
      APP: jellyseerr
      UPSTREAM: Fallenbagel/jellyseerr
    secrets: inherit