name: Build All          
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  bazarr:
    uses: ./.github/workflows/build.yml
    with:
      APP: bazarr
      UPSTREAM: morpheus65535/bazarr
    secrets: inherit     

  stash:
    needs: bazarr
    uses: ./.github/workflows/build.yml
    with:
      APP: stash
      UPSTREAM: stashapp/stash
    secrets: inherit     

  jellyseerr:
    needs: stash
    uses: ./.github/workflows/build.yml
    with:
      APP: jellyseerr
      UPSTREAM: fallenbagel/jellyseerr
    secrets: inherit     

  tautulli:
    needs: jellyseerr
    uses: ./.github/workflows/build.yml
    with:
      APP: tautulli
      UPSTREAM: tautulli/tautulli
    secrets: inherit     

