# .github/workflows/pages.yml
name: Publish Repository
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build All"]
    types: [completed]

jobs:
  publish-repository:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    container: alpine:latest
    permissions:
      contents: write 
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Install abuild + apk-tools
      run: apk add --no-cache alpine-sdk apk-tools openssl tar gzip git curl jq bash abuild python3

    - name: Checkout main branch (for scripts)
      uses: actions/checkout@v4
      with:
        path: main

    - name: Create empty directory for the repository
      run: mkdir -p final_repo
        
    - name: Restore package cache
      uses: actions/cache/restore@v4
      with:
        path: final_repo/main/x86_64
        key: apk-packages-${{ github.run_number }} 
        restore-keys: |
          apk-packages-

    - name: Publish repository
      id: publish
      env:
        GH_TOKEN:          ${{ secrets.GITHUB_TOKEN }}
        PACKAGER_PRIVKEY: ${{ secrets.PACKAGER_PRIVKEY }}
        KEY_NAME:         ${{ secrets.KEY_NAME }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        FORCE_REINDEX: ${{ github.event_name == 'workflow_dispatch' && 'true' || 'false' }}
      run: |
        chmod +x main/scripts/publish-repo.sh
        main/scripts/publish-repo.sh final_repo

    - name: Save package cache
      uses: actions/cache/save@v4
      if: steps.publish.outputs.reindex == 'true'
      with:
        path: final_repo/main/x86_64
        key: apk-packages-${{ github.run_number }}

    - name: Configure GitHub Pages
      if: steps.publish.outputs.reindex == 'true'
      uses: actions/configure-pages@v4

    - name: Upload Pages artifact
      if: steps.publish.outputs.reindex == 'true'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./final_repo

    - name: Deploy to GitHub Pages
      if: steps.publish.outputs.reindex == 'true'
      id: deployment
      uses: actions/deploy-pages@v4