#!/sbin/openrc-run
# /etc/init.d/jellyseerr

name="seerr"
description="seerr Service"

command_user="${command_user:-seerr:seerr}"
CONFIG_DIRECTORY="${CONFIG_DIRECTORY:-/var/lib/seerr}"
NODE_ENV="${NODE_ENV:-production}"

supervisor="supervise-daemon"
command="/usr/bin/seerr"
respawn_delay=5
respawn_max=10

depend() {
	need net
    use logger
}

start_pre() {
    checkpath --directory --mode 0755 --owner "${command_user}" "${CONFIG_DIRECTORY}"

    export NODE_ENV
    export CONFIG_DIRECTORY
}